import type { CrimeBreakdown } from "@/lib/types";

export type WardSeed = {
  id: string;
  name: string;
  neighborhoods: string;
  population: number;
  breakdown: CrimeBreakdown;
  topConcerns: string[];
};

// Auto-generated by scripts/generate_ward_seed.mjs — do not hand-edit.
// Per-ward values are editorial estimates assigned by distance-from-
// centroid tier; the calibration step in lib/wards.ts rescales them
// to match real city totals when monthly_stats.json has data.
export const WARDS_SEED: WardSeed[] = [
  {
    id: "10889",
    name: "Ward 10889",
    neighborhoods: "Ward 10889",
    population: 2914,
    breakdown: { theft: 4, robbery: 1, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10890",
    name: "Ward 10890",
    neighborhoods: "Ward 10890",
    population: 2692,
    breakdown: { theft: 3, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10901",
    name: "Ward 10901",
    neighborhoods: "Ward 10901",
    population: 2848,
    breakdown: { theft: 4, robbery: 0, assault: 0, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "10891",
    name: "Ward 10891",
    neighborhoods: "Ward 10891",
    population: 2795,
    breakdown: { theft: 3, robbery: 0, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10892",
    name: "Ward 10892",
    neighborhoods: "Ward 10892",
    population: 3093,
    breakdown: { theft: 3, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10906",
    name: "Ward 10906",
    neighborhoods: "Ward 10906",
    population: 2689,
    breakdown: { theft: 4, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "10893",
    name: "Ward 10893",
    neighborhoods: "Ward 10893",
    population: 3013,
    breakdown: { theft: 3, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10894",
    name: "Ward 10894",
    neighborhoods: "Ward 10894",
    population: 3180,
    breakdown: { theft: 4, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "10895",
    name: "Ward 10895",
    neighborhoods: "Ward 10895",
    population: 2663,
    breakdown: { theft: 5, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "10896",
    name: "Ward 10896",
    neighborhoods: "Ward 10896",
    population: 2831,
    breakdown: { theft: 3, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10903",
    name: "Ward 10903",
    neighborhoods: "Ward 10903",
    population: 2988,
    breakdown: { theft: 4, robbery: 1, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10897",
    name: "Ward 10897",
    neighborhoods: "Ward 10897",
    population: 3227,
    breakdown: { theft: 5, robbery: 1, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "10898",
    name: "Ward 10898",
    neighborhoods: "Ward 10898",
    population: 2960,
    breakdown: { theft: 4, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "10904",
    name: "Ward 10904",
    neighborhoods: "Ward 10904",
    population: 3307,
    breakdown: { theft: 5, robbery: 1, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10899",
    name: "Ward 10899",
    neighborhoods: "Ward 10899",
    population: 3154,
    breakdown: { theft: 4, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "10900",
    name: "Ward 10900",
    neighborhoods: "Ward 10900",
    population: 3300,
    breakdown: { theft: 3, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10902",
    name: "Ward 10902",
    neighborhoods: "Ward 10902",
    population: 2813,
    breakdown: { theft: 3, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10905",
    name: "Ward 10905",
    neighborhoods: "Ward 10905",
    population: 2728,
    breakdown: { theft: 2, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "10907",
    name: "Ward 10907",
    neighborhoods: "Ward 10907",
    population: 2728,
    breakdown: { theft: 4, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "12643",
    name: "Ward 12643",
    neighborhoods: "Ward 12643",
    population: 3160,
    breakdown: { theft: 2, robbery: 1, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
];
