import type { CrimeBreakdown } from "@/lib/types";

export type WardSeed = {
  id: string;
  name: string;
  neighborhoods: string;
  population: number;
  breakdown: CrimeBreakdown;
  topConcerns: string[];
};

// Auto-generated by scripts/generate_ward_seed.mjs — do not hand-edit.
// Per-ward values are editorial estimates assigned by distance-from-
// centroid tier; the calibration step in lib/wards.ts rescales them
// to match real city totals when monthly_stats.json has data.
export const WARDS_SEED: WardSeed[] = [
  {
    id: "10909",
    name: "Naga Bazar Ward",
    neighborhoods: "Naga Bazar Ward",
    population: 4762,
    breakdown: { theft: 5, robbery: 1, assault: 1, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10917",
    name: "Chandmari Upper Ward",
    neighborhoods: "Chandmari Upper Ward",
    population: 4803,
    breakdown: { theft: 6, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 2, other: 3 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10908",
    name: "Daklane Ward",
    neighborhoods: "Daklane Ward",
    population: 5658,
    breakdown: { theft: 8, robbery: 1, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "10920",
    name: "High School Ward",
    neighborhoods: "High School Ward",
    population: 5679,
    breakdown: { theft: 4, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 1, other: 4 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
  {
    id: "10910",
    name: "Kitsubozou Ward",
    neighborhoods: "Kitsubozou Ward",
    population: 5100,
    breakdown: { theft: 4, robbery: 1, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10912",
    name: "New Market Ward",
    neighborhoods: "New Market Ward",
    population: 4881,
    breakdown: { theft: 9, robbery: 1, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 2, other: 3 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "10911",
    name: "P.R. Hill Colony Ward",
    neighborhoods: "P.R. Hill Colony Ward",
    population: 4589,
    breakdown: { theft: 5, robbery: 1, assault: 1, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10926",
    name: "Hospital Colony Ward",
    neighborhoods: "Hospital Colony Ward",
    population: 5414,
    breakdown: { theft: 10, robbery: 1, assault: 1, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 2, other: 4 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "10913",
    name: "D. Block Ward",
    neighborhoods: "D. Block Ward",
    population: 4914,
    breakdown: { theft: 6, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10914",
    name: "Porterlane Ward",
    neighborhoods: "Porterlane Ward",
    population: 5194,
    breakdown: { theft: 4, robbery: 1, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "10915",
    name: "P.W.D Colony Ward",
    neighborhoods: "P.W.D Colony Ward",
    population: 4732,
    breakdown: { theft: 6, robbery: 1, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "10925",
    name: "Chandmari Lower Colony Ward",
    neighborhoods: "Chandmari Lower Colony Ward",
    population: 4684,
    breakdown: { theft: 5, robbery: 1, assault: 1, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10916",
    name: "Agri/Forest/Electrical Colony Ward",
    neighborhoods: "Agri/Forest/Electrical Colony Ward",
    population: 5259,
    breakdown: { theft: 5, robbery: 1, assault: 2, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 2, other: 3 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "10918",
    name: "Para Medical Colony Ward",
    neighborhoods: "Para Medical Colony Ward",
    population: 4699,
    breakdown: { theft: 7, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 2, other: 4 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10919",
    name: "Bayavu Colony Ward",
    neighborhoods: "Bayavu Colony Ward",
    population: 5438,
    breakdown: { theft: 4, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 1, other: 4 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
  {
    id: "10921",
    name: "Midlane Ward",
    neighborhoods: "Midlane Ward",
    population: 5773,
    breakdown: { theft: 10, robbery: 1, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 2, other: 3 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "10922",
    name: "North Block Ward",
    neighborhoods: "North Block Ward",
    population: 5543,
    breakdown: { theft: 5, robbery: 1, assault: 2, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 2, other: 3 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "10923",
    name: "A.G Colony Ward",
    neighborhoods: "A.G Colony Ward",
    population: 4978,
    breakdown: { theft: 5, robbery: 1, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10924",
    name: "New Ministers Hill/Lerie/D Farm",
    neighborhoods: "New Ministers Hill/Lerie/D Farm",
    population: 5666,
    breakdown: { theft: 6, robbery: 1, assault: 3, sexual_offence: 1, harassment: 4, kidnapping: 1, burglary: 2, other: 5 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
];
