import type { CrimeBreakdown } from "@/lib/types";

export type WardSeed = {
  id: string;
  name: string;
  neighborhoods: string;
  population: number;
  breakdown: CrimeBreakdown;
  topConcerns: string[];
};

// Auto-generated by scripts/generate_ward_seed.mjs — do not hand-edit.
// Per-ward values are editorial estimates assigned by distance-from-
// centroid tier; the calibration step in lib/wards.ts rescales them
// to match real city totals when monthly_stats.json has data.
export const WARDS_SEED: WardSeed[] = [
  {
    id: "1982",
    name: "Ward No 14",
    neighborhoods: "Ward No 14",
    population: 16108,
    breakdown: { theft: 21, robbery: 4, assault: 7, sexual_offence: 2, harassment: 8, kidnapping: 1, burglary: 7, other: 15 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "1974",
    name: "Ward No 7",
    neighborhoods: "Ward No 7",
    population: 16101,
    breakdown: { theft: 12, robbery: 3, assault: 6, sexual_offence: 2, harassment: 7, kidnapping: 1, burglary: 4, other: 11 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
  {
    id: "1975",
    name: "Ward No 5",
    neighborhoods: "Ward No 5",
    population: 14513,
    breakdown: { theft: 23, robbery: 2, assault: 3, sexual_offence: 1, harassment: 6, kidnapping: 1, burglary: 4, other: 8 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "1966",
    name: "Ward No 2",
    neighborhoods: "Ward No 2",
    population: 14225,
    breakdown: { theft: 12, robbery: 2, assault: 4, sexual_offence: 1, harassment: 5, kidnapping: 1, burglary: 4, other: 8 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "1967",
    name: "Ward No 3",
    neighborhoods: "Ward No 3",
    population: 17171,
    breakdown: { theft: 23, robbery: 3, assault: 6, sexual_offence: 2, harassment: 10, kidnapping: 1, burglary: 6, other: 12 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "1977",
    name: "Ward No 6",
    neighborhoods: "Ward No 6",
    population: 14510,
    breakdown: { theft: 13, robbery: 3, assault: 5, sexual_offence: 2, harassment: 5, kidnapping: 1, burglary: 5, other: 9 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "1968",
    name: "Ward No 4",
    neighborhoods: "Ward No 4",
    population: 14988,
    breakdown: { theft: 19, robbery: 3, assault: 5, sexual_offence: 2, harassment: 9, kidnapping: 1, burglary: 5, other: 10 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "1969",
    name: "Ward No 8",
    neighborhoods: "Ward No 8",
    population: 14616,
    breakdown: { theft: 15, robbery: 2, assault: 4, sexual_offence: 2, harassment: 7, kidnapping: 1, burglary: 4, other: 8 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "1970",
    name: "Ward No 9",
    neighborhoods: "Ward No 9",
    population: 15229,
    breakdown: { theft: 17, robbery: 2, assault: 2, sexual_offence: 1, harassment: 4, kidnapping: 0, burglary: 3, other: 6 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "1973",
    name: "Ward No 1",
    neighborhoods: "Ward No 1",
    population: 16190,
    breakdown: { theft: 18, robbery: 4, assault: 9, sexual_offence: 4, harassment: 11, kidnapping: 2, burglary: 6, other: 16 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
  {
    id: "1971",
    name: "Ward No 17",
    neighborhoods: "Ward No 17",
    population: 14972,
    breakdown: { theft: 22, robbery: 3, assault: 6, sexual_offence: 2, harassment: 10, kidnapping: 1, burglary: 5, other: 12 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "1972",
    name: "Ward No 16",
    neighborhoods: "Ward No 16",
    population: 16256,
    breakdown: { theft: 23, robbery: 3, assault: 6, sexual_offence: 2, harassment: 10, kidnapping: 1, burglary: 6, other: 12 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "1976",
    name: "Ward No 11",
    neighborhoods: "Ward No 11",
    population: 16393,
    breakdown: { theft: 18, robbery: 4, assault: 9, sexual_offence: 4, harassment: 11, kidnapping: 2, burglary: 6, other: 16 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
  {
    id: "1978",
    name: "Ward No 13",
    neighborhoods: "Ward No 13",
    population: 14965,
    breakdown: { theft: 20, robbery: 2, assault: 3, sexual_offence: 1, harassment: 5, kidnapping: 1, burglary: 4, other: 7 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "1979",
    name: "Ward No 10",
    neighborhoods: "Ward No 10",
    population: 16828,
    breakdown: { theft: 17, robbery: 3, assault: 6, sexual_offence: 2, harassment: 7, kidnapping: 1, burglary: 6, other: 12 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "1980",
    name: "Ward No 12",
    neighborhoods: "Ward No 12",
    population: 14389,
    breakdown: { theft: 29, robbery: 3, assault: 4, sexual_offence: 1, harassment: 7, kidnapping: 1, burglary: 5, other: 10 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "1981",
    name: "Ward No 18",
    neighborhoods: "Ward No 18",
    population: 14298,
    breakdown: { theft: 16, robbery: 3, assault: 6, sexual_offence: 2, harassment: 6, kidnapping: 1, burglary: 6, other: 11 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "1983",
    name: "Ward No 15",
    neighborhoods: "Ward No 15",
    population: 14486,
    breakdown: { theft: 10, robbery: 2, assault: 5, sexual_offence: 2, harassment: 6, kidnapping: 1, burglary: 3, other: 9 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
  {
    id: "1984",
    name: "Ward No 19",
    neighborhoods: "Ward No 19",
    population: 16674,
    breakdown: { theft: 11, robbery: 3, assault: 6, sexual_offence: 2, harassment: 7, kidnapping: 1, burglary: 4, other: 10 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
];
