import type { CrimeBreakdown } from "@/lib/types";

export type WardSeed = {
  id: string;
  name: string;
  neighborhoods: string;
  population: number;
  breakdown: CrimeBreakdown;
  topConcerns: string[];
};

// Auto-generated by scripts/generate_ward_seed.mjs — do not hand-edit.
// Per-ward values are editorial estimates assigned by distance-from-
// centroid tier; the calibration step in lib/wards.ts rescales them
// to match real city totals when monthly_stats.json has data.
export const WARDS_SEED: WardSeed[] = [
  {
    id: "9120836",
    name: "Tibet Road Ward",
    neighborhoods: "Tibet Road Ward",
    population: 6001,
    breakdown: { theft: 8, robbery: 1, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "9120837",
    name: "Chandmari Ward",
    neighborhoods: "Chandmari Ward",
    population: 6242,
    breakdown: { theft: 6, robbery: 1, assault: 2, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 2, other: 4 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "9120838",
    name: "Development Area",
    neighborhoods: "Development Area",
    population: 7366,
    breakdown: { theft: 11, robbery: 2, assault: 3, sexual_offence: 1, harassment: 5, kidnapping: 1, burglary: 3, other: 6 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "9120839",
    name: "DPH Ward",
    neighborhoods: "DPH Ward",
    population: 6528,
    breakdown: { theft: 8, robbery: 1, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "9120840",
    name: "Upper M G Marg",
    neighborhoods: "Upper M G Marg",
    population: 6306,
    breakdown: { theft: 13, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 2, other: 4 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "9120841",
    name: "Lower M G Marg",
    neighborhoods: "Lower M G Marg",
    population: 6844,
    breakdown: { theft: 11, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 2, other: 4 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "9120842",
    name: "Syari-Tathangchen",
    neighborhoods: "Syari-Tathangchen",
    population: 5966,
    breakdown: { theft: 5, robbery: 1, assault: 1, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "9120843",
    name: "Burtuk Ward",
    neighborhoods: "Burtuk Ward",
    population: 6773,
    breakdown: { theft: 7, robbery: 2, assault: 4, sexual_offence: 1, harassment: 4, kidnapping: 1, burglary: 2, other: 6 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
  {
    id: "9120844",
    name: "Lower Sichey",
    neighborhoods: "Lower Sichey",
    population: 5941,
    breakdown: { theft: 9, robbery: 1, assault: 2, sexual_offence: 1, harassment: 4, kidnapping: 0, burglary: 2, other: 5 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "9120845",
    name: "Upper Sichey",
    neighborhoods: "Upper Sichey",
    population: 6641,
    breakdown: { theft: 7, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 2, other: 4 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "9120846",
    name: "Arithang",
    neighborhoods: "Arithang",
    population: 7370,
    breakdown: { theft: 13, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 2, other: 5 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "9120847",
    name: "Tadong Ward",
    neighborhoods: "Tadong Ward",
    population: 6493,
    breakdown: { theft: 7, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 2, other: 5 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "9120848",
    name: "Daragaon Ward",
    neighborhoods: "Daragaon Ward",
    population: 5982,
    breakdown: { theft: 8, robbery: 1, assault: 2, sexual_offence: 1, harassment: 4, kidnapping: 0, burglary: 2, other: 4 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "9120849",
    name: "Deorali Ward",
    neighborhoods: "Deorali Ward",
    population: 6342,
    breakdown: { theft: 6, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "9120850",
    name: "Ranipool Ward",
    neighborhoods: "Ranipool Ward",
    population: 7390,
    breakdown: { theft: 5, robbery: 1, assault: 3, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 2, other: 5 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
];
