// @generated by scripts/codegen_cities.mjs — DO NOT EDIT.
// Source of truth: data/cities.manifest.json. Run `npm run codegen:cities`.


import mumbaiJson from "@/data/cities/mumbai/absconders.json";
import bangaloreJson from "@/data/cities/bangalore/absconders.json";
import delhiJson from "@/data/cities/delhi/absconders.json";
import chennaiJson from "@/data/cities/chennai/absconders.json";
import hyderabadJson from "@/data/cities/hyderabad/absconders.json";
import kolkataJson from "@/data/cities/kolkata/absconders.json";
import puneJson from "@/data/cities/pune/absconders.json";
import gurugramJson from "@/data/cities/gurugram/absconders.json";
import noidaJson from "@/data/cities/noida/absconders.json";
import ahmedabadJson from "@/data/cities/ahmedabad/absconders.json";
import coimbatoreJson from "@/data/cities/coimbatore/absconders.json";
import indoreJson from "@/data/cities/indore/absconders.json";
import jaipurJson from "@/data/cities/jaipur/absconders.json";
import suratJson from "@/data/cities/surat/absconders.json";
import lucknowJson from "@/data/cities/lucknow/absconders.json";
import kochiJson from "@/data/cities/kochi/absconders.json";
import nagpurJson from "@/data/cities/nagpur/absconders.json";
import kanpurJson from "@/data/cities/kanpur/absconders.json";
import bhubaneswarJson from "@/data/cities/bhubaneswar/absconders.json";

import type { CityId } from "./cities.generated";

export const ABSCONDERS_JSON: Record<CityId, unknown> = {
  mumbai: mumbaiJson,
  bangalore: bangaloreJson,
  delhi: delhiJson,
  chennai: chennaiJson,
  hyderabad: hyderabadJson,
  kolkata: kolkataJson,
  pune: puneJson,
  gurugram: gurugramJson,
  noida: noidaJson,
  ahmedabad: ahmedabadJson,
  coimbatore: coimbatoreJson,
  indore: indoreJson,
  jaipur: jaipurJson,
  surat: suratJson,
  lucknow: lucknowJson,
  kochi: kochiJson,
  nagpur: nagpurJson,
  kanpur: kanpurJson,
  bhubaneswar: bhubaneswarJson,
};
