// @generated by scripts/codegen_cities.mjs — DO NOT EDIT.
// Source of truth: data/cities.manifest.json. Run `npm run codegen:cities`.


import mumbaiJson from "@/data/cities/mumbai/absconders.json";
import bangaloreJson from "@/data/cities/bangalore/absconders.json";
import delhiJson from "@/data/cities/delhi/absconders.json";
import chennaiJson from "@/data/cities/chennai/absconders.json";
import hyderabadJson from "@/data/cities/hyderabad/absconders.json";
import kolkataJson from "@/data/cities/kolkata/absconders.json";
import puneJson from "@/data/cities/pune/absconders.json";
import gurugramJson from "@/data/cities/gurugram/absconders.json";
import noidaJson from "@/data/cities/noida/absconders.json";

import type { CityId } from "./cities.generated";

export const ABSCONDERS_JSON: Record<CityId, unknown> = {
  mumbai: mumbaiJson,
  bangalore: bangaloreJson,
  delhi: delhiJson,
  chennai: chennaiJson,
  hyderabad: hyderabadJson,
  kolkata: kolkataJson,
  pune: puneJson,
  gurugram: gurugramJson,
  noida: noidaJson,
};
