// @generated by scripts/codegen_cities.mjs — DO NOT EDIT.
// Source of truth: data/cities.manifest.json. Run `npm run codegen:cities`.


import { WARDS_SEED as MUMBAI_SEED } from "@/data/cities/mumbai/wards-raw";
import { WARDS_SEED as BANGALORE_SEED } from "@/data/cities/bangalore/wards-raw";
import { WARDS_SEED as DELHI_SEED } from "@/data/cities/delhi/wards-raw";
import { WARDS_SEED as CHENNAI_SEED } from "@/data/cities/chennai/wards-raw";
import { WARDS_SEED as HYDERABAD_SEED } from "@/data/cities/hyderabad/wards-raw";
import { WARDS_SEED as KOLKATA_SEED } from "@/data/cities/kolkata/wards-raw";
import { WARDS_SEED as PUNE_SEED } from "@/data/cities/pune/wards-raw";
import { WARDS_SEED as GURUGRAM_SEED } from "@/data/cities/gurugram/wards-raw";
import { WARDS_SEED as NOIDA_SEED } from "@/data/cities/noida/wards-raw";

import mumbaiStatsJson from "@/data/cities/mumbai/monthly_stats.json";
import bangaloreStatsJson from "@/data/cities/bangalore/monthly_stats.json";
import delhiStatsJson from "@/data/cities/delhi/monthly_stats.json";
import chennaiStatsJson from "@/data/cities/chennai/monthly_stats.json";
import hyderabadStatsJson from "@/data/cities/hyderabad/monthly_stats.json";
import kolkataStatsJson from "@/data/cities/kolkata/monthly_stats.json";
import puneStatsJson from "@/data/cities/pune/monthly_stats.json";
import gurugramStatsJson from "@/data/cities/gurugram/monthly_stats.json";
import noidaStatsJson from "@/data/cities/noida/monthly_stats.json";

import mumbaiHistoryJson from "@/data/cities/mumbai/monthly_stats_history.json";
import bangaloreHistoryJson from "@/data/cities/bangalore/monthly_stats_history.json";
import delhiHistoryJson from "@/data/cities/delhi/monthly_stats_history.json";
import chennaiHistoryJson from "@/data/cities/chennai/monthly_stats_history.json";
import hyderabadHistoryJson from "@/data/cities/hyderabad/monthly_stats_history.json";
import kolkataHistoryJson from "@/data/cities/kolkata/monthly_stats_history.json";
import puneHistoryJson from "@/data/cities/pune/monthly_stats_history.json";
import gurugramHistoryJson from "@/data/cities/gurugram/monthly_stats_history.json";
import noidaHistoryJson from "@/data/cities/noida/monthly_stats_history.json";

import mumbaiNewsJson from "@/data/cities/mumbai/ward_news.json";
import bangaloreNewsJson from "@/data/cities/bangalore/ward_news.json";
import delhiNewsJson from "@/data/cities/delhi/ward_news.json";
import chennaiNewsJson from "@/data/cities/chennai/ward_news.json";
import hyderabadNewsJson from "@/data/cities/hyderabad/ward_news.json";
import kolkataNewsJson from "@/data/cities/kolkata/ward_news.json";
import puneNewsJson from "@/data/cities/pune/ward_news.json";
import gurugramNewsJson from "@/data/cities/gurugram/ward_news.json";
import noidaNewsJson from "@/data/cities/noida/ward_news.json";

import type { WardSeed } from "@/data/cities/mumbai/wards-raw";
import type { CityId } from "./cities.generated";

export type { WardSeed };

export const SEEDS: Record<CityId, WardSeed[]> = {
  mumbai: MUMBAI_SEED,
  bangalore: BANGALORE_SEED,
  delhi: DELHI_SEED,
  chennai: CHENNAI_SEED,
  hyderabad: HYDERABAD_SEED,
  kolkata: KOLKATA_SEED,
  pune: PUNE_SEED,
  gurugram: GURUGRAM_SEED,
  noida: NOIDA_SEED,
};

export const STATS_JSON: Record<CityId, unknown> = {
  mumbai: mumbaiStatsJson,
  bangalore: bangaloreStatsJson,
  delhi: delhiStatsJson,
  chennai: chennaiStatsJson,
  hyderabad: hyderabadStatsJson,
  kolkata: kolkataStatsJson,
  pune: puneStatsJson,
  gurugram: gurugramStatsJson,
  noida: noidaStatsJson,
};

export const HISTORY_JSON: Record<CityId, unknown> = {
  mumbai: mumbaiHistoryJson,
  bangalore: bangaloreHistoryJson,
  delhi: delhiHistoryJson,
  chennai: chennaiHistoryJson,
  hyderabad: hyderabadHistoryJson,
  kolkata: kolkataHistoryJson,
  pune: puneHistoryJson,
  gurugram: gurugramHistoryJson,
  noida: noidaHistoryJson,
};

export const NEWS_JSON: Record<CityId, unknown> = {
  mumbai: mumbaiNewsJson,
  bangalore: bangaloreNewsJson,
  delhi: delhiNewsJson,
  chennai: chennaiNewsJson,
  hyderabad: hyderabadNewsJson,
  kolkata: kolkataNewsJson,
  pune: puneNewsJson,
  gurugram: gurugramNewsJson,
  noida: noidaNewsJson,
};
