import type { CrimeBreakdown } from "@/lib/types";

export type WardSeed = {
  id: string;
  name: string;
  neighborhoods: string;
  population: number;
  breakdown: CrimeBreakdown;
  topConcerns: string[];
};

// Auto-generated by scripts/generate_ward_seed.mjs — do not hand-edit.
// Per-ward values are editorial estimates assigned by distance-from-
// centroid tier; the calibration step in lib/wards.ts rescales them
// to match real city totals when monthly_stats.json has data.
export const WARDS_SEED: WardSeed[] = [
  {
    id: "4651",
    name: "Ward No 7",
    neighborhoods: "Ward No 7",
    population: 5175,
    breakdown: { theft: 6, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 2, other: 4 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "4646",
    name: "Ward No 1",
    neighborhoods: "Ward No 1",
    population: 5890,
    breakdown: { theft: 4, robbery: 1, assault: 2, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 1, other: 4 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
  {
    id: "4647",
    name: "Ward No 3",
    neighborhoods: "Ward No 3",
    population: 7104,
    breakdown: { theft: 4, robbery: 1, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "4648",
    name: "Ward No 4",
    neighborhoods: "Ward No 4",
    population: 7501,
    breakdown: { theft: 4, robbery: 1, assault: 2, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 2, other: 3 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "4649",
    name: "Ward No 5",
    neighborhoods: "Ward No 5",
    population: 5352,
    breakdown: { theft: 4, robbery: 1, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "4650",
    name: "Ward No 6",
    neighborhoods: "Ward No 6",
    population: 4598,
    breakdown: { theft: 7, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 2, other: 4 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "4652",
    name: "Ward No 8",
    neighborhoods: "Ward No 8",
    population: 5343,
    breakdown: { theft: 5, robbery: 1, assault: 2, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 2, other: 3 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "4654",
    name: "Ward No 10",
    neighborhoods: "Ward No 10",
    population: 10675,
    breakdown: { theft: 4, robbery: 1, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "4664",
    name: "Ward No 21",
    neighborhoods: "Ward No 21",
    population: 4459,
    breakdown: { theft: 7, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 2, other: 4 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "4665",
    name: "Ward No 22",
    neighborhoods: "Ward No 22",
    population: 4356,
    breakdown: { theft: 4, robbery: 1, assault: 2, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
  {
    id: "4653",
    name: "Ward No 9",
    neighborhoods: "Ward No 9",
    population: 6274,
    breakdown: { theft: 7, robbery: 1, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "4655",
    name: "Ward No 11",
    neighborhoods: "Ward No 11",
    population: 5681,
    breakdown: { theft: 5, robbery: 1, assault: 2, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 2, other: 4 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "4656",
    name: "Ward No 13",
    neighborhoods: "Ward No 13",
    population: 4095,
    breakdown: { theft: 5, robbery: 1, assault: 1, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "4657",
    name: "Ward No 14",
    neighborhoods: "Ward No 14",
    population: 3937,
    breakdown: { theft: 8, robbery: 1, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "4658",
    name: "Ward No 15",
    neighborhoods: "Ward No 15",
    population: 3910,
    breakdown: { theft: 8, robbery: 1, assault: 1, sexual_offence: 0, harassment: 2, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "4667",
    name: "Ward No 23",
    neighborhoods: "Ward No 23",
    population: 4652,
    breakdown: { theft: 5, robbery: 1, assault: 3, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 2, other: 5 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
  {
    id: "4662",
    name: "Ward No 19",
    neighborhoods: "Ward No 19",
    population: 4745,
    breakdown: { theft: 6, robbery: 1, assault: 2, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 2, other: 4 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "4659",
    name: "Ward No 16",
    neighborhoods: "Ward No 16",
    population: 4375,
    breakdown: { theft: 6, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "4660",
    name: "Ward No 17",
    neighborhoods: "Ward No 17",
    population: 9952,
    breakdown: { theft: 6, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 2, other: 4 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "4663",
    name: "Ward No 20",
    neighborhoods: "Ward No 20",
    population: 4537,
    breakdown: { theft: 5, robbery: 1, assault: 2, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 2, other: 4 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "4661",
    name: "Ward No 18",
    neighborhoods: "Ward No 18",
    population: 6443,
    breakdown: { theft: 5, robbery: 1, assault: 2, sexual_offence: 1, harassment: 3, kidnapping: 0, burglary: 2, other: 4 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
  {
    id: "4666",
    name: "Ward No 24",
    neighborhoods: "Ward No 24",
    population: 4116,
    breakdown: { theft: 4, robbery: 1, assault: 2, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 1, other: 4 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
  {
    id: "12291",
    name: "Ward No 2",
    neighborhoods: "Ward No 2",
    population: 7329,
    breakdown: { theft: 3, robbery: 1, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "12292",
    name: "Ward No 12",
    neighborhoods: "Ward No 12",
    population: 4424,
    breakdown: { theft: 5, robbery: 1, assault: 1, sexual_offence: 1, harassment: 2, kidnapping: 0, burglary: 1, other: 3 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
];
