#!/usr/bin/env node
// Generates lib/cities.generated.ts, lib/wards.generated.ts,
// lib/absconders.generated.ts from data/cities.manifest.json.
//
// Idempotent — running it twice with the same manifest produces identical
// output. Wired into the `prebuild` npm script so `next build` is always
// preceded by a fresh codegen.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const MANIFEST_PATH = resolve(ROOT, "data/cities.manifest.json");

const REQUIRED_FIELDS = [
  "id", "name", "state", "stateCode", "tier",
  "center", "bounds", "geojson", "wardIdKey", "unit",
  "hasMonthlyStats", "hasAbsconders",
];
const VALID_TIERS = new Set(["capital", "million_plus", "both"]);

function validate(manifest) {
  if (!Array.isArray(manifest)) {
    throw new Error("manifest must be a JSON array of city entries");
  }
  const ids = new Set();
  for (const [i, c] of manifest.entries()) {
    for (const f of REQUIRED_FIELDS) {
      if (!(f in c)) throw new Error(`row ${i} (${c.id ?? "?"}): missing field "${f}"`);
    }
    if (!/^[a-z][a-z0-9_]*$/.test(c.id)) {
      throw new Error(`row ${i}: id "${c.id}" must be lowercase snake (a-z0-9_)`);
    }
    if (ids.has(c.id)) throw new Error(`duplicate id: ${c.id}`);
    ids.add(c.id);
    if (!VALID_TIERS.has(c.tier)) {
      throw new Error(`${c.id}: tier "${c.tier}" not in ${[...VALID_TIERS].join("|")}`);
    }
    if (!Array.isArray(c.center) || c.center.length !== 2) {
      throw new Error(`${c.id}: center must be [lon, lat]`);
    }
    if (!Array.isArray(c.bounds) || c.bounds.length !== 2) {
      throw new Error(`${c.id}: bounds must be [[w,s],[e,n]]`);
    }
  }
  return manifest;
}

function header(generator) {
  return `// @generated by scripts/${generator} — DO NOT EDIT.
// Source of truth: data/cities.manifest.json. Run \`npm run codegen:cities\`.

`;
}

function constantCase(id) {
  return id.toUpperCase().replace(/-/g, "_");
}

function emitCities(manifest) {
  const lines = [];
  lines.push(header("codegen_cities.mjs"));
  lines.push(`import type { CityConfig } from "./cities";\n`);
  lines.push(`export type CityId =`);
  manifest.forEach((c, i) => {
    const sep = i === manifest.length - 1 ? ";" : "";
    lines.push(`  | "${c.id}"${sep}`);
  });
  lines.push("");
  lines.push(`export const CITY_IDS: readonly CityId[] = [`);
  manifest.forEach((c) => lines.push(`  "${c.id}",`));
  lines.push(`] as const;`);
  lines.push("");
  lines.push(`export const CITIES: Record<CityId, CityConfig> = {`);
  for (const c of manifest) {
    lines.push(`  ${c.id}: {`);
    lines.push(`    id: "${c.id}",`);
    lines.push(`    name: ${JSON.stringify(c.name)},`);
    if (c.nameI18n && Object.keys(c.nameI18n).length > 0) {
      lines.push(`    nameI18n: ${JSON.stringify(c.nameI18n)},`);
    }
    lines.push(`    state: ${JSON.stringify(c.state)},`);
    lines.push(`    stateCode: ${JSON.stringify(c.stateCode)},`);
    lines.push(`    tier: ${JSON.stringify(c.tier)},`);
    lines.push(`    center: [${c.center[0]}, ${c.center[1]}],`);
    lines.push(`    bounds: [[${c.bounds[0][0]}, ${c.bounds[0][1]}], [${c.bounds[1][0]}, ${c.bounds[1][1]}]],`);
    lines.push(`    geojson: ${JSON.stringify(c.geojson)},`);
    lines.push(`    wardIdKey: ${JSON.stringify(c.wardIdKey)},`);
    lines.push(`    unit: ${JSON.stringify(c.unit)},`);
    lines.push(`    hasMonthlyStats: ${c.hasMonthlyStats},`);
    lines.push(`    hasAbsconders: ${c.hasAbsconders},`);
    lines.push(`  },`);
  }
  lines.push(`};`);
  lines.push("");
  return lines.join("\n");
}

function emitWards(manifest) {
  const lines = [];
  lines.push(header("codegen_cities.mjs"));
  // Seed imports
  for (const c of manifest) {
    lines.push(`import { WARDS_SEED as ${constantCase(c.id)}_SEED } from "@/data/cities/${c.id}/wards-raw";`);
  }
  lines.push("");
  // Stats imports
  for (const c of manifest) {
    lines.push(`import ${c.id}StatsJson from "@/data/cities/${c.id}/monthly_stats.json";`);
  }
  lines.push("");
  // History imports
  for (const c of manifest) {
    lines.push(`import ${c.id}HistoryJson from "@/data/cities/${c.id}/monthly_stats_history.json";`);
  }
  lines.push("");
  // News imports
  for (const c of manifest) {
    lines.push(`import ${c.id}NewsJson from "@/data/cities/${c.id}/ward_news.json";`);
  }
  lines.push("");
  lines.push(`import type { WardSeed } from "@/data/cities/${manifest[0].id}/wards-raw";`);
  lines.push(`import type { CityId } from "./cities.generated";`);
  lines.push("");
  lines.push(`export type { WardSeed };`);
  lines.push("");
  lines.push(`export const SEEDS: Record<CityId, WardSeed[]> = {`);
  for (const c of manifest) lines.push(`  ${c.id}: ${constantCase(c.id)}_SEED,`);
  lines.push(`};`);
  lines.push("");
  lines.push(`export const STATS_JSON: Record<CityId, unknown> = {`);
  for (const c of manifest) lines.push(`  ${c.id}: ${c.id}StatsJson,`);
  lines.push(`};`);
  lines.push("");
  lines.push(`export const HISTORY_JSON: Record<CityId, unknown> = {`);
  for (const c of manifest) lines.push(`  ${c.id}: ${c.id}HistoryJson,`);
  lines.push(`};`);
  lines.push("");
  lines.push(`export const NEWS_JSON: Record<CityId, unknown> = {`);
  for (const c of manifest) lines.push(`  ${c.id}: ${c.id}NewsJson,`);
  lines.push(`};`);
  lines.push("");
  return lines.join("\n");
}

function emitAbsconders(manifest) {
  const lines = [];
  lines.push(header("codegen_cities.mjs"));
  for (const c of manifest) {
    lines.push(`import ${c.id}Json from "@/data/cities/${c.id}/absconders.json";`);
  }
  lines.push("");
  lines.push(`import type { CityId } from "./cities.generated";`);
  lines.push("");
  lines.push(`export const ABSCONDERS_JSON: Record<CityId, unknown> = {`);
  for (const c of manifest) lines.push(`  ${c.id}: ${c.id}Json,`);
  lines.push(`};`);
  lines.push("");
  return lines.join("\n");
}

function writeIfChanged(path, content) {
  if (existsSync(path) && readFileSync(path, "utf8") === content) {
    return { path, changed: false };
  }
  writeFileSync(path, content);
  return { path, changed: true };
}

function main() {
  const manifest = validate(JSON.parse(readFileSync(MANIFEST_PATH, "utf8")));
  const results = [
    writeIfChanged(resolve(ROOT, "lib/cities.generated.ts"), emitCities(manifest)),
    writeIfChanged(resolve(ROOT, "lib/wards.generated.ts"), emitWards(manifest)),
    writeIfChanged(resolve(ROOT, "lib/absconders.generated.ts"), emitAbsconders(manifest)),
  ];
  const changed = results.filter((r) => r.changed).map((r) => r.path.replace(`${ROOT}/`, ""));
  if (changed.length === 0) {
    console.log(`codegen_cities: no changes (${manifest.length} cities)`);
  } else {
    console.log(`codegen_cities: regenerated ${changed.length} file(s) from ${manifest.length} cities`);
    for (const p of changed) console.log(`  - ${p}`);
  }
}

main();
