import type { CrimeBreakdown } from "@/lib/types";

export type WardSeed = {
  id: string;
  name: string;
  neighborhoods: string;
  population: number;
  breakdown: CrimeBreakdown;
  topConcerns: string[];
};

// Auto-generated by scripts/generate_ward_seed.mjs — do not hand-edit.
// Per-ward values are editorial estimates assigned by distance-from-
// centroid tier; the calibration step in lib/wards.ts rescales them
// to match real city totals when monthly_stats.json has data.
export const WARDS_SEED: WardSeed[] = [
  {
    id: "10079",
    name: "Ward 10079",
    neighborhoods: "Ward 10079",
    population: 2179,
    breakdown: { theft: 2, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "10080",
    name: "Ward 10080",
    neighborhoods: "Ward 10080",
    population: 2118,
    breakdown: { theft: 4, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "10069",
    name: "Ward 10069",
    neighborhoods: "Ward 10069",
    population: 2202,
    breakdown: { theft: 2, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Peripheral lanes very isolated at night", "Higher rates of reported violent incidents per capita"],
  },
  {
    id: "10072",
    name: "Ward 10072",
    neighborhoods: "Ward 10072",
    population: 2260,
    breakdown: { theft: 4, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "10078",
    name: "Ward 10078",
    neighborhoods: "Ward 10078",
    population: 2113,
    breakdown: { theft: 2, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10068",
    name: "Ward 10068",
    neighborhoods: "Ward 10068",
    population: 2557,
    breakdown: { theft: 3, robbery: 1, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "10077",
    name: "Ward 10077",
    neighborhoods: "Ward 10077",
    population: 2452,
    breakdown: { theft: 3, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 2 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10070",
    name: "Ward 10070",
    neighborhoods: "Ward 10070",
    population: 2330,
    breakdown: { theft: 2, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Suburban service-road stretches isolated late at night", "Snatching reported along highway approaches"],
  },
  {
    id: "10071",
    name: "Ward 10071",
    neighborhoods: "Ward 10071",
    population: 2615,
    breakdown: { theft: 3, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10073",
    name: "Ward 10073",
    neighborhoods: "Ward 10073",
    population: 2534,
    breakdown: { theft: 4, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "10074",
    name: "Ward 10074",
    neighborhoods: "Ward 10074",
    population: 2382,
    breakdown: { theft: 4, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Higher pedestrian foot-traffic — pickpocketing & chain-snatching", "Isolated late-night stretches near transit interchanges"],
  },
  {
    id: "10075",
    name: "Ward 10075",
    neighborhoods: "Ward 10075",
    population: 2238,
    breakdown: { theft: 2, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
  {
    id: "10076",
    name: "Ward 10076",
    neighborhoods: "Ward 10076",
    population: 2573,
    breakdown: { theft: 2, robbery: 0, assault: 1, sexual_offence: 0, harassment: 1, kidnapping: 0, burglary: 1, other: 1 },
    topConcerns: ["Mixed residential/commercial — opportunistic theft", "Sub-station road stretches poorly lit at night"],
  },
];
